# Розбір html-файлів - 2

In [ ]:
import pandas as pd
import html5lib
from bs4 import BeautifulSoup
from pathlib import Path
import lxml

In [ ]:
fname = Path('prepare', 'bbb.html')
with open(fname,  encoding='utf-8') as f:
    data = f.read()

In [ ]:
soup = BeautifulSoup(data, 'html5lib')

Наявну у html-файлі таблиці можна завантажити в таблицю вручну, якщо спочатку завантажити її у структуру даних Python, а потім за ціює структурою побудувати об'єкт типу <code>DataFrame</code>.

Тег <code>tbody</code> позначає тіло таблиці, тег <code>tr</code> &mdash; рядок таблиці, <code>th</code> &mdash; клітину заголовку, <code>td</code> &mdash; звичайну клітину.

In [ ]:
columns = ["Date", "Open", "High", "Low", "Close", "Volume", 'Adj_Close']
loaded = {el:[] for el in columns}
for row in soup.find("tbody").find_all('tr'):
    col = row.find_all("td")
    if (col != []):
        for i, el in enumerate(columns):
            loaded[el].append(col[i].text)

netflix_data = pd.DataFrame(loaded)
netflix_data.head()

           Date    Open    High     Low   Close  Volume    Adj_Close
0  Jun 01, 2021  504.01  536.13  482.14  528.21  528.21   78,560,600
1  May 01, 2021  512.65  518.95  478.54  502.81  502.81   66,927,600
2  Apr 01, 2021  529.93  563.56  499.00  513.47  513.47  111,573,300
3  Mar 01, 2021  545.57  556.99  492.85  521.66  521.66   90,183,900
4  Feb 01, 2021  536.79  566.65  518.28  538.85  538.85   61,902,300

Насправді, таблиці можна завантажувати напряму з <code>html</code>-файлу чи навіть з URL. За умовчанням використовується парсер <code>lxml</code>.

Функція <code>pandas.read_html</code> (<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_html.html#pandas.read_html" target=_blank rel="noopener noreferrer">документація</a>) повертаэ список завантажених таблиць.

In [ ]:
read_html_pandas_data = pd.read_html(fname)
read_html_pandas_data[0]

,Date,Open,High,Low,Close*,Adj Close**,Volume
0,"Jun 01, 2021",504.01,536.13,482.14,528.21,528.21,78560600
1,"May 01, 2021",512.65,518.95,478.54,502.81,502.81,66927600
2,"Apr 01, 2021",529.93,563.56,499.00,513.47,513.47,111573300
3,"Mar 01, 2021",545.57,556.99,492.85,521.66,521.66,90183900
4,"Feb 01, 2021",536.79,566.65,518.28,538.85,538.85,61902300
...,...,...,...,...,...,...,...
66,"Dec 01, 2015",124.47,133.27,113.85,114.38,114.38,319939200
67,"Nov 01, 2015",109.20,126.60,101.86,123.33,123.33,320321800
68,"Oct 01, 2015",102.91,115.83,96.26,108.38,108.38,446204400
69,"Sep 01, 2015",109.35,111.24,93.55,103.26,103.26,497401200
70,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...,*Close price adjusted for splits.**Adjusted cl...