Виконавець:  <b>Базилевич Олексій Андрійович</b>, група <b>К-27</b>
<br> Викладач: <b>Андрій Ляшко</b>
Частина 1

Варіант 4 (Local Cheese)

Знайти країну де найдешевше та найдорожче

Надати інформацію про: кількість наявних даних, найменшу та найбільшу вартість (в EUR) та на якому місті вони досягаються

In [1]:
from pathlib import Path
import io
import json
import pandas as pd
import sys
import requests
import bs4
from bs4 import BeautifulSoup as BSoup, SoupStrainer, BeautifulSoup
import html5lib

In [4]:
url = "https://www.numbeo.com/cost-of-living/prices_by_country.jsp?displayCurrency=EUR&itemId=12"
r = requests.get(url)
r.status_code

200

In [6]:
fname = Path('data.html')
cheese_data = r.text
with open(fname, "w", encoding="utf-8") as f:
    f.write(cheese_data)

In [8]:
with open(fname,"r" ,encoding="utf-8") as f:
    data = f.read()
data

'<!DOCTYPE html>\n<html lang="en-US">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n\n<meta name="description" content="See current prices by country for prices of items we do track. You can see prices only for countries where we have decent number of contributors." />\n            <script defer src="https://www.numbeo.com/common/numbeo_standard.js"></script>\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">\n    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/themes/redmond/jquery-ui.min.css" rel="Stylesheet" />\n    <link rel="shortcut icon" type="image/x-icon" href="https://www.numbeo.com/favicon.ico" />\n    <script  defer  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>\n    <script  defer  src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>\n   <script src=\'https://www.gstatic.com/charts/loader.js\'></script>\n<link rel="apple-touch-icon" href="https://www.numbeo.com/images/apple-touch-icon.png">\n  <script>\n  if (typeof whenDocReady === "function") {\n    // already declared, do nothing\n  } else {\n    function whenDocReady(fn) {\n      // see if DOM is already available\n      if (document.readyState === "complete" || document.readyState === "interactive") {\n        // call on next available tick\n        setTimeout(fn, 1);\n      } else {\n        document.addEventListener("DOMContentLoaded", fn);\n      }\n    }\n  }\n</script>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-HXEZG0C6Q2"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\ngtag(\'config\', \'G-HXEZG0C6Q2\');\ngtag(\'set\', \'user_properties\', { ab: \'0\'});\n</script>\n<link rel="stylesheet" href="https://cdn.datatables.net/v/ju/dt-1.10.22/datatables.min.css"/>\n<script defer src="https://cdn.datatables.net/v/ju/dt-1.10.22/datatables.min.js"></script>\n<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8993465169534557"\n     crossorigin="anonymous"></script>\n\n\n\n    <link rel="stylesheet" href="https://www.numbeo.com/common/style_desktop.css" />\n\n  <script>\n\n    function checkControls() {\n\n      enableIfElementsHaveSomeValue("calculate", /* to check */ "itemId", "displayCurrency");\n\n    }\n\n  </script>\n\n<link rel="canonical" href="https://www.numbeo.com/cost-of-living/prices_by_country.jsp?itemId=12" />\n  <title>Prices by Country of Local Cheese (1 kg) (Markets)</title>\n\n</head>\n\n<body>\n\n<nav>\n<div class="logo-and-upper-ad">\n<div class="innerWidth" id="content_and_logo">\n<table style="width: 100%;" >\n<tr>\n<td style="padding-top: 14px; padding-bottom: 16px; vertical-align: bottom; max-width: fit-content" class="container_around_logo_desktop">\n<a href="https://www.numbeo.com/cost-of-living/" style="border: 0; text-decoration:none;">\n<img src="https://www.numbeo.com/images/numbeo_1B3B6F.svg" style="height: 60px; padding: 0px 0px; vertical-align: bottom; border: 0;" alt="" /></a>\n</td>\n<td style="padding-left:40px; padding-top: 5px; padding-bottom: 0px; vertical-align: middle; min-width: 440px; text-align: left;" >\n<div style="display: inline-block; width: 100%; margin-top: 10px; margin-bottom: 10px; text-align: left; vertical-align: bottom">\n<nav style="display: inline-block; vertical-align: middle;">\n<div class="standard_margin_inlineblock" >      <form action="https://www.numbeo.com/common/dispatcher.jsp" method="get" id="menu_dispatch_form"  style="display: inline; padding: 0; margin:0;">\n      <input type="hidden" name="where" value="https://www.numbeo.com/cost-of-living/in/" style="display: inline; padding:0; margin:0;" />\n<input id="city_selector_menu_city_id"  size="27"  type="text" placeholder="Select City" class="city-selector-menu" name="city_selector_menu_city_id" />\n<input type="hidden" id="menu_city_id" name="city_id"/>\n<input type="hidden" id="name_menu_city_id" name="name_city_id"/>\n      </form>\n</div>\n <script>\nwhenDocReady(function() {\n  \tjQuery(\'#city_selector_menu_city_id\').autocomplete({\n  \t  source: \'https://www.numbeo.com/common/CitySearchJson\',\n     minLength: 1,\n     delay: 3,\n     autoFocus: true,\n     select: function(event, ui) {\n         event.preventDefault();\n         $(\'#name_menu_city_id\').val(ui.item.label);\n         $(\'#city_selector_menu_city_id\').val(ui.item.label);\n         $(\'#menu_city_id\').val(ui.item.value);\njQuery(\'#menu_dispatch_form\').submit();     },\n     focus: function(event, ui) {\n         event.preventDefault();\n     }\n\t  })   .keydown(function(e){\n\t    if (e.keyCode === 13){\n      if ($(\'#menu_city_id\').val() == \'\') { \n        e.preventDefault();\n      }\n      var val = $(\'#city_selector_menu_city_id\').val();\n\t\t   $(\'#name_menu_city_id\').val(val);\n\t   }\n  }); // end autocompleter definition\n$(\'#city_selector_menu_city_id\').toggleClass(\'city-selector-menu\');\n$(\'#city_selector_menu_city_id\').toggleClass(\'city-selector-menu\');\n }); // end document ready \n</script>\n</nav>\n</div>\n</td>\n<td style="vertical-align: middle; width: 468px; text-align: right;" >\n</td>\n</tr>\n</table>\n</div> <!-- innerWidth in header -->\n</div> <!-- logo-and-upper-ad -->\n</nav>\n<div class="innerWidth">\n<div class="dropdown-outer">\n<nav class="before-nav" >\n    <ul id="nav-one" class="nav">\n\n\t<li class="dir">\n<a href="https://www.numbeo.com/cost-of-living/">Cost Of Living</a>\n  <ul>\n    <li><a href="https://www.numbeo.com/cost-of-living/">Cost Of Living</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/comparison.jsp">Cost of Living Comparison</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/calculator.jsp">Cost of Living Calculator</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/rankings_current.jsp">Cost Of Living Index (Current)</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/rankings.jsp">Cost Of Living Index</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/rankings_by_country.jsp">Cost Of Living Index By Country</a></li>\n    <li><a href="https://www.numbeo.com/food-prices/">Food Prices</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/prices_by_city.jsp">Prices By City</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/prices_by_country.jsp">Prices By Country</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/basket_of_goods.jsp">Basket of Goods and Services</a></li>\n    <li><a href="https://www.numbeo.com/taxi-fare/">Taxi Fare Calculator</a></li>\n    <li><a href="https://www.numbeo.com/gas-prices/">Gas Prices Calculator</a></li>\n    <li><a href="https://www.numbeo.com/common/motivation_and_methodology.jsp">Methodology and Motivation</a></li>\n    <li><a href="https://www.numbeo.com/salary-calculator/">Salary Calculator</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/contribute.jsp">Update Data for Your City</a></li>\n  </ul></li>\n\n\t<li class="dir">\n<a href="https://www.numbeo.com/property-investment/">Property Prices</a>\n  <ul>\n    <li><a href="https://www.numbeo.com/property-investment/">Property Prices</a></li>\n    <li><a href="https://www.numbeo.com/property-investment/comparison.jsp">Property Prices Comparison</a></li>\n    <li><a href="https://www.numbeo.com/property-investment/rankings_current.jsp">Property Price Index (Current)</a></li>\n    <li><a href="https://www.numbeo.com/property-investment/rankings.jsp">Property Price Index</a></li>\n    <li><a href="https://www.numbeo.com/property-investment/rankings_by_country.jsp">Property Price Index By Country</a></li>\n   </ul></li>\n\n\t<li class="dir">\n<a href="https://www.numbeo.com/quality-of-life/">Quality Of Life</a>\n  <ul>\n    <li><a href="https://www.numbeo.com/quality-of-life/">Quality of Life</a></li>\n    <li><a href="https://www.numbeo.com/quality-of-life/comparison.jsp">Quality of Life Comparisons</a></li>\n    <li><a href="https://www.numbeo.com/quality-of-life/rankings_current.jsp">Quality of Life Index (Current)</a></li>\n    <li><a href="https://www.numbeo.com/quality-of-life/rankings.jsp">Quality of Life Index</a></li>\n    <li><a href="https://www.numbeo.com/quality-of-life/rankings_by_country.jsp">Quality of Life Index by Country</a></li>\n    <li><a href="https://www.numbeo.com/crime/">Crime</a></li>\n    <li><a href="https://www.numbeo.com/crime/rankings_current.jsp">Crime Index (Current)</a></li>\n    <li><a href="https://www.numbeo.com/crime/rankings.jsp">Crime Index</a></li>\n    <li><a href="https://www.numbeo.com/crime/rankings_by_country.jsp">Crime Index by Country</a></li>\n    <li><a href="https://www.numbeo.com/health-care/">Health Care</a></li>\n    <li><a href="https://www.numbeo.com/health-care/rankings_current.jsp">Health Care Index (Current)</a></li>\n    <li><a href="https://www.numbeo.com/health-care/rankings.jsp">Health Care Index</a></li>\n    <li><a href="https://www.numbeo.com/health-care/rankings_by_country.jsp">Health Care Index by Country</a></li>\n    <li><a href="https://www.numbeo.com/pollution/">Pollution</a></li>\n    <li><a href="https://www.numbeo.com/pollution/rankings_current.jsp">Pollution Index (Current)</a></li>\n    <li><a href="https://www.numbeo.com/pollution/rankings.jsp">Pollution Index</a></li>\n    <li><a href="https://www.numbeo.com/pollution/rankings_by_country.jsp">Pollution Index by Country</a></li>\n     <li><a href="https://www.numbeo.com/traffic/">Traffic</a></li>\n     <li><a href="https://www.numbeo.com/traffic/rankings_current.jsp">Traffic Index (Current)</a></li>\n     <li><a href="https://www.numbeo.com/traffic/rankings.jsp">Traffic Index</a></li>\n     <li><a href="https://www.numbeo.com/traffic/rankings_by_country.jsp">Traffic Index by Country</a></li>\n\t</ul></li>\n\t<li class="dir">\n<a href="https://www.numbeo.com/premium/index">Premium</a>\n  <ul>\n    <li><a href="https://www.numbeo.com/common/api.jsp">Data API</a></li>\n    <li><a href="https://www.numbeo.com/premium/commercial-license">Data License</a></li>\n    <li><a href="https://www.numbeo.com/premium/download-data">Bulk Data Download</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/historical-data-analysis">Historical Data Explorer</a></li>\n    <li><a href="https://www.numbeo.com/cost-of-living/estimator_main">Cost of Living Estimator</a></li>\n    <li><a href="https://www.numbeo.com/premium/">Insight Reports</a></li>\n    <li><a href="https://www.numbeo.com/premium/international-salary-equivalent-calculator">Global Salary Equivalent Calculator</a></li>\n    <li><a href="https://www.numbeo.com/premium/relocation-salary-calculator">Relocation Salary Calculator</a></li>\n\t</ul></li>\n\n\n</ul>\n<br style="clear: both"/>\n</nav>\n</div> <!-- dropdown-outer -->\n</div> <!-- innerWidth -->\n<div class="innerWidth">\n <div class="right-ads-and-info">\n <div class="right-ads">\n </div>\n </div>\n<p>\n<nav itemscope itemtype="http://schema.org/BreadcrumbList" class="breadcrumb">\n<a href="https://www.numbeo.com/common/" class="discreet_link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" class="image_without_border hide_smaller_than_600" style="vertical-align: text-bottom" viewBox="0 0 24 24"><path fill="#1B3B6F" d="M10 20v-6h4v6h5v-8h3L12 3L2 12h3v8z"/></svg></a><span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">\n<a href="https://www.numbeo.com/cost-of-living/" itemprop="item" class="breadcrumb_link"><span itemprop="name">Cost of Living</span></a><meta itemprop="position" content="1" />\n</span> <span style="font-size: 75%; display: inline-block;">&gt;</span> <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">\n <a href="https://www.numbeo.com/cost-of-living/prices_by_country.jsp"  itemprop="item"  class="breadcrumb_link"><span itemprop="name">Prices by Country</span></a><meta itemprop="position" content="2" />\n</span> <span style="font-size: 75%; display: inline-block;">&gt;</span> <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">\n<a href="https://www.numbeo.com/cost-of-living/prices_by_country.jsp?itemId=12"  itemprop="item"  class="breadcrumb_link">\n<span itemprop="name">Local Cheese (1 kg) (Markets)</span></a><meta itemprop="position" content="3" />\n</span></nav>\n    <h1> Prices by Country of Local Cheese (1 kg) (Markets)</h1>\n\n\n<!-- Column 1 start -->\n\n\n<div id="page_container">\n\nThis page displays current price data by country.\n<br/>Data are displayed only for countries with a sufficient number of contributors.\n<br/>\n\n<div class="fancy_explanation" style="margin-bottom: 0.8em; width: fit-content;">\n<a href="https://www.numbeo.com/cost-of-living/country_price_rankings?displayCurrency=EUR&amp;itemId=12">See bar chart of these data</a></div>\n\n<div class="regionChartDivContainer">\n<div id="chart_div_12" class="regionChartDiv" ></div><div class="regionChartDivLabel">\nChart: Local Cheese (1 kg), Markets</div>\n</div>\n <script>\n     google.load(\'visualization\', \'1\', {\'packages\': [\'geochart\']});\n     google.setOnLoadCallback(drawRegionsMap_12);\n\n      function drawRegionsMap_12() {\n        var data = new google.visualization.DataTable();\n        data.addColumn(\'string\', \'Country\');\n        data.addColumn(\'number\', \'Local Cheese (1 kg), Markets\');\n        data.addRows([\n        [\'Switzerland\', 23.56],\n        [\'Hong Kong (China)\', 19.71],\n        [\'Luxembourg\', 18.54],\n        [\'Austria\', 17.42],\n        [\'France\', 17.22],\n        [\'Singapore\', 15.72],\n        [\'Israel\', 15.69],\n        [\'Taiwan\', 15.58],\n        [\'Italy\', 14.97],\n        [\'Thailand\', 14.95],\n        [\'Belgium\', 13.53],\n        [\'Slovenia\', 13.10],\n        [\'Denmark\', 12.98],\n        [\'Germany\', 12.87],\n        [\'Spain\', 12.42],\n        [\'Slovakia\', 12.41],\n        [\'Netherlands\', 12.39],\n        [\'Greece\', 12.05],\n        [\'Malaysia\', 12.05],\n        [\'Uruguay\', 11.85],\n        [\'Cyprus\', 11.81],\n        [\'United States\', 11.34],\n        [\'China\', 11.27],\n        [\'South Korea\', 11.20],\n        [\'Norway\', 11.18],\n        [\'Czech Republic\', 11.10],\n        [\'Sweden\', 10.80],\n        [\'Croatia\', 10.65],\n        [\'Albania\', 10.64],\n        [\'Sri Lanka\', 10.54],\n        [\'Estonia\', 10.44],\n        [\'Lithuania\', 10.24],\n        [\'Portugal\', 10.24],\n        [\'Panama\', 10.17],\n        [\'Vietnam\', 10.04],\n        [\'Ireland\', 9.85],\n        [\'Russia\', 9.67],\n        [\'Canada\', 9.51],\n        [\'Tunisia\', 9.50],\n        [\'Latvia\', 9.49],\n        [\'Japan\', 9.44],\n        [\'Malta\', 9.43],\n        [\'United Arab Emirates\', 9.43],\n        [\'Chile\', 9.41],\n        [\'Bulgaria\', 9.38],\n        [\'Qatar\', 9.29],\n        [\'Puerto Rico\', 9.17],\n        [\'Zimbabwe\', 9.16],\n        [\'Morocco\', 9.13],\n        [\'Kenya\', 8.70],\n        [\'Hungary\', 8.57],\n        [\'Serbia\', 8.57],\n        [\'Australia\', 8.57],\n        [\'Argentina\', 8.52],\n        [\'Kazakhstan\', 8.50],\n        [\'Bahrain\', 8.49],\n        [\'United Kingdom\', 8.32],\n        [\'Turkey\', 8.24],\n        [\'Costa Rica\', 8.22],\n        [\'Moldova\', 8.16],\n        [\'Bosnia And Herzegovina\', 8.04],\n        [\'Mexico\', 8.03],\n        [\'Mauritius\', 7.99],\n        [\'Montenegro\', 7.99],\n        [\'Poland\', 7.97],\n        [\'Brazil\', 7.85],\n        [\'Lebanon\', 7.68],\n        [\'North Macedonia\', 7.68],\n        [\'Algeria\', 7.67],\n        [\'Finland\', 7.67],\n        [\'Ukraine\', 7.65],\n        [\'Romania\', 7.65],\n        [\'Indonesia\', 7.45],\n        [\'Dominican Republic\', 7.17],\n        [\'New Zealand\', 7.11],\n        [\'South Africa\', 7.05],\n        [\'Peru\', 7.03],\n        [\'Uzbekistan\', 7.01],\n        [\'Bangladesh\', 6.96],\n        [\'Belarus\', 6.73],\n        [\'Philippines\', 6.54],\n        [\'Saudi Arabia\', 6.47],\n        [\'Armenia\', 6.46],\n        [\'Georgia\', 6.39],\n        [\'Oman\', 6.23],\n        [\'Nepal\', 6.10],\n        [\'Kosovo (Disputed Territory)\', 5.80],\n        [\'Venezuela\', 5.67],\n        [\'Jordan\', 5.59],\n        [\'Ecuador\', 5.41],\n        [\'Kuwait\', 5.24],\n        [\'Pakistan\', 5.10],\n        [\'Cuba\', 5.03],\n        [\'Nigeria\', 4.99],\n        [\'Colombia\', 4.72],\n        [\'Bolivia\', 4.32],\n        [\'India\', 4.14],\n        [\'Iraq\', 4.12],\n        [\'Azerbaijan\', 3.83],\n        [\'Iran\', 3.43],\n        [\'Egypt\', 2.98],\n        ]);\n\n        var options = {\n          colorAxis: {colors: [ \'#1a9641\', \'#a6d96a\', \'#ffffbf\', \'#fdae61\', \'#d7191c\']}\n        };\n\n        var chart = new google.visualization.GeoChart(document.getElementById(\'chart_div_12\'));\n        chart.draw(data, options);\n    };\n    </script>\n\n\n<form action="prices_by_country.jsp" method="get" class="standard_margin">\n<input type="hidden" name="itemId" value="12" />\nCurrency:          <select id="displayCurrency" name="displayCurrency" onchange="if (checkSelectedSomeTextNotDashed(\'displayCurrency\')) this.form.submit();">\n             <option value="EUR" selected="selected">EUR</option>\n             <option value="USD">USD</option>\n             <option value="---">---</option>\n             <option value="AED">AED</option>\n             <option value="AFN">AFN</option>\n             <option value="ALL">ALL</option>\n             <option value="AMD">AMD</option>\n             <option value="ANG">ANG</option>\n             <option value="AOA">AOA</option>\n             <option value="ARS">ARS</option>\n             <option value="AUD">AUD</option>\n             <option value="AWG">AWG</option>\n             <option value="AZN">AZN</option>\n             <option value="BAM">BAM</option>\n             <option value="BBD">BBD</option>\n             <option value="BDT">BDT</option>\n             <option value="BGN">BGN</option>\n             <option value="BHD">BHD</option>\n             <option value="BIF">BIF</option>\n             <option value="BMD">BMD</option>\n             <option value="BND">BND</option>\n             <option value="BOB">BOB</option>\n             <option value="BRL">BRL</option>\n             <option value="BSD">BSD</option>\n             <option value="BTC">BTC</option>\n             <option value="BTN">BTN</option>\n             <option value="BWP">BWP</option>\n             <option value="BYN">BYN</option>\n             <option value="BZD">BZD</option>\n             <option value="CAD">CAD</option>\n             <option value="CDF">CDF</option>\n             <option value="CHF">CHF</option>\n             <option value="CLF">CLF</option>\n             <option value="CLP">CLP</option>\n             <option value="CNH">CNH</option>\n             <option value="CNY">CNY</option>\n             <option value="COP">COP</option>\n             <option value="CRC">CRC</option>\n             <option value="CUC">CUC</option>\n             <option value="CVE">CVE</option>\n             <option value="CZK">CZK</option>\n             <option value="DJF">DJF</option>\n             <option value="DKK">DKK</option>\n             <option value="DOP">DOP</option>\n             <option value="EGP">EGP</option>\n             <option value="ERN">ERN</option>\n             <option value="EUR">EUR</option>\n             <option value="FJD">FJD</option>\n             <option value="FKP">FKP</option>\n             <option value="GBP">GBP</option>\n             <

In [9]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(data, "html.parser")

In [13]:
tables = soup.find_all("table")
table_index = None
for index,table in enumerate(tables):
    if'Local Cheese ' in str(table):
        table_index = index
        break
table_index

1

In [23]:
cheese = pd.read_html(io.StringIO(str(tables[table_index])), flavor = 'bs4')[0]
cheese

     Rank             Country  Local Cheese (1 kg)
0     NaN          Kazakhstan                 8.50
1     NaN            Portugal                10.24
2     NaN              Greece                12.05
3     NaN              Latvia                 9.49
4     NaN                Iran                 3.43
..    ...                 ...                  ...
96    NaN  Dominican Republic                 7.17
97    NaN              Mexico                 8.03
98    NaN            Zimbabwe                 9.16
99    NaN          Montenegro                 7.99
100   NaN           Indonesia                 7.45

[101 rows x 3 columns]

In [29]:
min_val = cheese["Local Cheese (1 kg)"].min()
min_row = cheese[cheese["Local Cheese (1 kg)"] == min_val]
min_row

    Rank Country  Local Cheese (1 kg)
76   NaN   Egypt                 2.98

In [30]:
max_val = cheese["Local Cheese (1 kg)"].max()
max_row = cheese[cheese["Local Cheese (1 kg)"] == max_val]
max_row

    Rank      Country  Local Cheese (1 kg)
42   NaN  Switzerland                23.56

In [31]:
print(len(cheese["Local Cheese (1 kg)"]))

101